/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConferenceConferenceIdRouteRouteImport } from './routes/conference/$conferenceId/route'
import { Route as ConferenceConferenceIdRoomsRouteImport } from './routes/conference/$conferenceId/rooms'
import { Route as ConferenceConferenceIdPublicMeetingsRouteImport } from './routes/conference/$conferenceId/public-meetings'
import { Route as ConferenceConferenceIdProfileRouteImport } from './routes/conference/$conferenceId/profile'
import { Route as ConferenceConferenceIdNotificationsRouteImport } from './routes/conference/$conferenceId/notifications'
import { Route as ConferenceConferenceIdConfigRouteImport } from './routes/conference/$conferenceId/config'
import { Route as ConferenceConferenceIdChatsRouteImport } from './routes/conference/$conferenceId/chats'
import { Route as ConferenceConferenceIdCalendarRouteImport } from './routes/conference/$conferenceId/calendar'
import { Route as ConferenceConferenceIdAttendeesRouteImport } from './routes/conference/$conferenceId/attendees'
import { Route as ConferenceConferenceIdMeetingMeetingIdRouteImport } from './routes/conference/$conferenceId/meeting.$meetingId'
import { Route as ConferenceConferenceIdChatChatRoomIdRouteImport } from './routes/conference/$conferenceId/chat.$chatRoomId'
import { Route as ConferenceConferenceIdAttendeeUserIdRouteImport } from './routes/conference/$conferenceId/attendee.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceConferenceIdRouteRoute =
  ConferenceConferenceIdRouteRouteImport.update({
    id: '/conference/$conferenceId',
    path: '/conference/$conferenceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConferenceConferenceIdRoomsRoute =
  ConferenceConferenceIdRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)
const ConferenceConferenceIdPublicMeetingsRoute =
  ConferenceConferenceIdPublicMeetingsRouteImport.update({
    id: '/public-meetings',
    path: '/public-meetings',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)
const ConferenceConferenceIdProfileRoute =
  ConferenceConferenceIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)
const ConferenceConferenceIdNotificationsRoute =
  ConferenceConferenceIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)
const ConferenceConferenceIdConfigRoute =
  ConferenceConferenceIdConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)
const ConferenceConferenceIdChatsRoute =
  ConferenceConferenceIdChatsRouteImport.update({
    id: '/chats',
    path: '/chats',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)
const ConferenceConferenceIdCalendarRoute =
  ConferenceConferenceIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)
const ConferenceConferenceIdAttendeesRoute =
  ConferenceConferenceIdAttendeesRouteImport.update({
    id: '/attendees',
    path: '/attendees',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)
const ConferenceConferenceIdMeetingMeetingIdRoute =
  ConferenceConferenceIdMeetingMeetingIdRouteImport.update({
    id: '/meeting/$meetingId',
    path: '/meeting/$meetingId',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)
const ConferenceConferenceIdChatChatRoomIdRoute =
  ConferenceConferenceIdChatChatRoomIdRouteImport.update({
    id: '/chat/$chatRoomId',
    path: '/chat/$chatRoomId',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)
const ConferenceConferenceIdAttendeeUserIdRoute =
  ConferenceConferenceIdAttendeeUserIdRouteImport.update({
    id: '/attendee/$userId',
    path: '/attendee/$userId',
    getParentRoute: () => ConferenceConferenceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conference/$conferenceId': typeof ConferenceConferenceIdRouteRouteWithChildren
  '/conference/$conferenceId/attendees': typeof ConferenceConferenceIdAttendeesRoute
  '/conference/$conferenceId/calendar': typeof ConferenceConferenceIdCalendarRoute
  '/conference/$conferenceId/chats': typeof ConferenceConferenceIdChatsRoute
  '/conference/$conferenceId/config': typeof ConferenceConferenceIdConfigRoute
  '/conference/$conferenceId/notifications': typeof ConferenceConferenceIdNotificationsRoute
  '/conference/$conferenceId/profile': typeof ConferenceConferenceIdProfileRoute
  '/conference/$conferenceId/public-meetings': typeof ConferenceConferenceIdPublicMeetingsRoute
  '/conference/$conferenceId/rooms': typeof ConferenceConferenceIdRoomsRoute
  '/conference/$conferenceId/attendee/$userId': typeof ConferenceConferenceIdAttendeeUserIdRoute
  '/conference/$conferenceId/chat/$chatRoomId': typeof ConferenceConferenceIdChatChatRoomIdRoute
  '/conference/$conferenceId/meeting/$meetingId': typeof ConferenceConferenceIdMeetingMeetingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conference/$conferenceId': typeof ConferenceConferenceIdRouteRouteWithChildren
  '/conference/$conferenceId/attendees': typeof ConferenceConferenceIdAttendeesRoute
  '/conference/$conferenceId/calendar': typeof ConferenceConferenceIdCalendarRoute
  '/conference/$conferenceId/chats': typeof ConferenceConferenceIdChatsRoute
  '/conference/$conferenceId/config': typeof ConferenceConferenceIdConfigRoute
  '/conference/$conferenceId/notifications': typeof ConferenceConferenceIdNotificationsRoute
  '/conference/$conferenceId/profile': typeof ConferenceConferenceIdProfileRoute
  '/conference/$conferenceId/public-meetings': typeof ConferenceConferenceIdPublicMeetingsRoute
  '/conference/$conferenceId/rooms': typeof ConferenceConferenceIdRoomsRoute
  '/conference/$conferenceId/attendee/$userId': typeof ConferenceConferenceIdAttendeeUserIdRoute
  '/conference/$conferenceId/chat/$chatRoomId': typeof ConferenceConferenceIdChatChatRoomIdRoute
  '/conference/$conferenceId/meeting/$meetingId': typeof ConferenceConferenceIdMeetingMeetingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conference/$conferenceId': typeof ConferenceConferenceIdRouteRouteWithChildren
  '/conference/$conferenceId/attendees': typeof ConferenceConferenceIdAttendeesRoute
  '/conference/$conferenceId/calendar': typeof ConferenceConferenceIdCalendarRoute
  '/conference/$conferenceId/chats': typeof ConferenceConferenceIdChatsRoute
  '/conference/$conferenceId/config': typeof ConferenceConferenceIdConfigRoute
  '/conference/$conferenceId/notifications': typeof ConferenceConferenceIdNotificationsRoute
  '/conference/$conferenceId/profile': typeof ConferenceConferenceIdProfileRoute
  '/conference/$conferenceId/public-meetings': typeof ConferenceConferenceIdPublicMeetingsRoute
  '/conference/$conferenceId/rooms': typeof ConferenceConferenceIdRoomsRoute
  '/conference/$conferenceId/attendee/$userId': typeof ConferenceConferenceIdAttendeeUserIdRoute
  '/conference/$conferenceId/chat/$chatRoomId': typeof ConferenceConferenceIdChatChatRoomIdRoute
  '/conference/$conferenceId/meeting/$meetingId': typeof ConferenceConferenceIdMeetingMeetingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conference/$conferenceId'
    | '/conference/$conferenceId/attendees'
    | '/conference/$conferenceId/calendar'
    | '/conference/$conferenceId/chats'
    | '/conference/$conferenceId/config'
    | '/conference/$conferenceId/notifications'
    | '/conference/$conferenceId/profile'
    | '/conference/$conferenceId/public-meetings'
    | '/conference/$conferenceId/rooms'
    | '/conference/$conferenceId/attendee/$userId'
    | '/conference/$conferenceId/chat/$chatRoomId'
    | '/conference/$conferenceId/meeting/$meetingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conference/$conferenceId'
    | '/conference/$conferenceId/attendees'
    | '/conference/$conferenceId/calendar'
    | '/conference/$conferenceId/chats'
    | '/conference/$conferenceId/config'
    | '/conference/$conferenceId/notifications'
    | '/conference/$conferenceId/profile'
    | '/conference/$conferenceId/public-meetings'
    | '/conference/$conferenceId/rooms'
    | '/conference/$conferenceId/attendee/$userId'
    | '/conference/$conferenceId/chat/$chatRoomId'
    | '/conference/$conferenceId/meeting/$meetingId'
  id:
    | '__root__'
    | '/'
    | '/conference/$conferenceId'
    | '/conference/$conferenceId/attendees'
    | '/conference/$conferenceId/calendar'
    | '/conference/$conferenceId/chats'
    | '/conference/$conferenceId/config'
    | '/conference/$conferenceId/notifications'
    | '/conference/$conferenceId/profile'
    | '/conference/$conferenceId/public-meetings'
    | '/conference/$conferenceId/rooms'
    | '/conference/$conferenceId/attendee/$userId'
    | '/conference/$conferenceId/chat/$chatRoomId'
    | '/conference/$conferenceId/meeting/$meetingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConferenceConferenceIdRouteRoute: typeof ConferenceConferenceIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference/$conferenceId': {
      id: '/conference/$conferenceId'
      path: '/conference/$conferenceId'
      fullPath: '/conference/$conferenceId'
      preLoaderRoute: typeof ConferenceConferenceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference/$conferenceId/rooms': {
      id: '/conference/$conferenceId/rooms'
      path: '/rooms'
      fullPath: '/conference/$conferenceId/rooms'
      preLoaderRoute: typeof ConferenceConferenceIdRoomsRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
    '/conference/$conferenceId/public-meetings': {
      id: '/conference/$conferenceId/public-meetings'
      path: '/public-meetings'
      fullPath: '/conference/$conferenceId/public-meetings'
      preLoaderRoute: typeof ConferenceConferenceIdPublicMeetingsRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
    '/conference/$conferenceId/profile': {
      id: '/conference/$conferenceId/profile'
      path: '/profile'
      fullPath: '/conference/$conferenceId/profile'
      preLoaderRoute: typeof ConferenceConferenceIdProfileRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
    '/conference/$conferenceId/notifications': {
      id: '/conference/$conferenceId/notifications'
      path: '/notifications'
      fullPath: '/conference/$conferenceId/notifications'
      preLoaderRoute: typeof ConferenceConferenceIdNotificationsRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
    '/conference/$conferenceId/config': {
      id: '/conference/$conferenceId/config'
      path: '/config'
      fullPath: '/conference/$conferenceId/config'
      preLoaderRoute: typeof ConferenceConferenceIdConfigRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
    '/conference/$conferenceId/chats': {
      id: '/conference/$conferenceId/chats'
      path: '/chats'
      fullPath: '/conference/$conferenceId/chats'
      preLoaderRoute: typeof ConferenceConferenceIdChatsRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
    '/conference/$conferenceId/calendar': {
      id: '/conference/$conferenceId/calendar'
      path: '/calendar'
      fullPath: '/conference/$conferenceId/calendar'
      preLoaderRoute: typeof ConferenceConferenceIdCalendarRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
    '/conference/$conferenceId/attendees': {
      id: '/conference/$conferenceId/attendees'
      path: '/attendees'
      fullPath: '/conference/$conferenceId/attendees'
      preLoaderRoute: typeof ConferenceConferenceIdAttendeesRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
    '/conference/$conferenceId/meeting/$meetingId': {
      id: '/conference/$conferenceId/meeting/$meetingId'
      path: '/meeting/$meetingId'
      fullPath: '/conference/$conferenceId/meeting/$meetingId'
      preLoaderRoute: typeof ConferenceConferenceIdMeetingMeetingIdRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
    '/conference/$conferenceId/chat/$chatRoomId': {
      id: '/conference/$conferenceId/chat/$chatRoomId'
      path: '/chat/$chatRoomId'
      fullPath: '/conference/$conferenceId/chat/$chatRoomId'
      preLoaderRoute: typeof ConferenceConferenceIdChatChatRoomIdRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
    '/conference/$conferenceId/attendee/$userId': {
      id: '/conference/$conferenceId/attendee/$userId'
      path: '/attendee/$userId'
      fullPath: '/conference/$conferenceId/attendee/$userId'
      preLoaderRoute: typeof ConferenceConferenceIdAttendeeUserIdRouteImport
      parentRoute: typeof ConferenceConferenceIdRouteRoute
    }
  }
}

interface ConferenceConferenceIdRouteRouteChildren {
  ConferenceConferenceIdAttendeesRoute: typeof ConferenceConferenceIdAttendeesRoute
  ConferenceConferenceIdCalendarRoute: typeof ConferenceConferenceIdCalendarRoute
  ConferenceConferenceIdChatsRoute: typeof ConferenceConferenceIdChatsRoute
  ConferenceConferenceIdConfigRoute: typeof ConferenceConferenceIdConfigRoute
  ConferenceConferenceIdNotificationsRoute: typeof ConferenceConferenceIdNotificationsRoute
  ConferenceConferenceIdProfileRoute: typeof ConferenceConferenceIdProfileRoute
  ConferenceConferenceIdPublicMeetingsRoute: typeof ConferenceConferenceIdPublicMeetingsRoute
  ConferenceConferenceIdRoomsRoute: typeof ConferenceConferenceIdRoomsRoute
  ConferenceConferenceIdAttendeeUserIdRoute: typeof ConferenceConferenceIdAttendeeUserIdRoute
  ConferenceConferenceIdChatChatRoomIdRoute: typeof ConferenceConferenceIdChatChatRoomIdRoute
  ConferenceConferenceIdMeetingMeetingIdRoute: typeof ConferenceConferenceIdMeetingMeetingIdRoute
}

const ConferenceConferenceIdRouteRouteChildren: ConferenceConferenceIdRouteRouteChildren =
  {
    ConferenceConferenceIdAttendeesRoute: ConferenceConferenceIdAttendeesRoute,
    ConferenceConferenceIdCalendarRoute: ConferenceConferenceIdCalendarRoute,
    ConferenceConferenceIdChatsRoute: ConferenceConferenceIdChatsRoute,
    ConferenceConferenceIdConfigRoute: ConferenceConferenceIdConfigRoute,
    ConferenceConferenceIdNotificationsRoute:
      ConferenceConferenceIdNotificationsRoute,
    ConferenceConferenceIdProfileRoute: ConferenceConferenceIdProfileRoute,
    ConferenceConferenceIdPublicMeetingsRoute:
      ConferenceConferenceIdPublicMeetingsRoute,
    ConferenceConferenceIdRoomsRoute: ConferenceConferenceIdRoomsRoute,
    ConferenceConferenceIdAttendeeUserIdRoute:
      ConferenceConferenceIdAttendeeUserIdRoute,
    ConferenceConferenceIdChatChatRoomIdRoute:
      ConferenceConferenceIdChatChatRoomIdRoute,
    ConferenceConferenceIdMeetingMeetingIdRoute:
      ConferenceConferenceIdMeetingMeetingIdRoute,
  }

const ConferenceConferenceIdRouteRouteWithChildren =
  ConferenceConferenceIdRouteRoute._addFileChildren(
    ConferenceConferenceIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConferenceConferenceIdRouteRoute:
    ConferenceConferenceIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
