/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as PublicMeetingsRouteImport } from './routes/public-meetings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AttendeesRouteImport } from './routes/attendees'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUserIdRouteImport } from './routes/user.$userId'
import { Route as MeetingMeetingIdRouteImport } from './routes/meeting.$meetingId'
import { Route as ChatChatRoomIdRouteImport } from './routes/chat.$chatRoomId'

const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicMeetingsRoute = PublicMeetingsRouteImport.update({
  id: '/public-meetings',
  path: '/public-meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesRoute = AttendeesRouteImport.update({
  id: '/attendees',
  path: '/attendees',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingMeetingIdRoute = MeetingMeetingIdRouteImport.update({
  id: '/meeting/$meetingId',
  path: '/meeting/$meetingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatRoomIdRoute = ChatChatRoomIdRouteImport.update({
  id: '/chat/$chatRoomId',
  path: '/chat/$chatRoomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/attendees': typeof AttendeesRoute
  '/calendar': typeof CalendarRoute
  '/chats': typeof ChatsRoute
  '/config': typeof ConfigRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/public-meetings': typeof PublicMeetingsRoute
  '/rooms': typeof RoomsRoute
  '/chat/$chatRoomId': typeof ChatChatRoomIdRoute
  '/meeting/$meetingId': typeof MeetingMeetingIdRoute
  '/user/$userId': typeof UserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/attendees': typeof AttendeesRoute
  '/calendar': typeof CalendarRoute
  '/chats': typeof ChatsRoute
  '/config': typeof ConfigRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/public-meetings': typeof PublicMeetingsRoute
  '/rooms': typeof RoomsRoute
  '/chat/$chatRoomId': typeof ChatChatRoomIdRoute
  '/meeting/$meetingId': typeof MeetingMeetingIdRoute
  '/user/$userId': typeof UserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/attendees': typeof AttendeesRoute
  '/calendar': typeof CalendarRoute
  '/chats': typeof ChatsRoute
  '/config': typeof ConfigRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/public-meetings': typeof PublicMeetingsRoute
  '/rooms': typeof RoomsRoute
  '/chat/$chatRoomId': typeof ChatChatRoomIdRoute
  '/meeting/$meetingId': typeof MeetingMeetingIdRoute
  '/user/$userId': typeof UserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/attendees'
    | '/calendar'
    | '/chats'
    | '/config'
    | '/notifications'
    | '/profile'
    | '/public-meetings'
    | '/rooms'
    | '/chat/$chatRoomId'
    | '/meeting/$meetingId'
    | '/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/attendees'
    | '/calendar'
    | '/chats'
    | '/config'
    | '/notifications'
    | '/profile'
    | '/public-meetings'
    | '/rooms'
    | '/chat/$chatRoomId'
    | '/meeting/$meetingId'
    | '/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/attendees'
    | '/calendar'
    | '/chats'
    | '/config'
    | '/notifications'
    | '/profile'
    | '/public-meetings'
    | '/rooms'
    | '/chat/$chatRoomId'
    | '/meeting/$meetingId'
    | '/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AttendeesRoute: typeof AttendeesRoute
  CalendarRoute: typeof CalendarRoute
  ChatsRoute: typeof ChatsRoute
  ConfigRoute: typeof ConfigRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  PublicMeetingsRoute: typeof PublicMeetingsRoute
  RoomsRoute: typeof RoomsRoute
  ChatChatRoomIdRoute: typeof ChatChatRoomIdRoute
  MeetingMeetingIdRoute: typeof MeetingMeetingIdRoute
  UserUserIdRoute: typeof UserUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-meetings': {
      id: '/public-meetings'
      path: '/public-meetings'
      fullPath: '/public-meetings'
      preLoaderRoute: typeof PublicMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees': {
      id: '/attendees'
      path: '/attendees'
      fullPath: '/attendees'
      preLoaderRoute: typeof AttendeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$meetingId': {
      id: '/meeting/$meetingId'
      path: '/meeting/$meetingId'
      fullPath: '/meeting/$meetingId'
      preLoaderRoute: typeof MeetingMeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatRoomId': {
      id: '/chat/$chatRoomId'
      path: '/chat/$chatRoomId'
      fullPath: '/chat/$chatRoomId'
      preLoaderRoute: typeof ChatChatRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AttendeesRoute: AttendeesRoute,
  CalendarRoute: CalendarRoute,
  ChatsRoute: ChatsRoute,
  ConfigRoute: ConfigRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  PublicMeetingsRoute: PublicMeetingsRoute,
  RoomsRoute: RoomsRoute,
  ChatChatRoomIdRoute: ChatChatRoomIdRoute,
  MeetingMeetingIdRoute: MeetingMeetingIdRoute,
  UserUserIdRoute: UserUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
